runtime: nodejs10
instance_class: F2

env_variables:
    PASSWD: vaalit2019
    BACKEND_URL: https://localhost:8080 # App Engine always runs on port 8080

automatic_scaling:
   target_cpu_utilization: 0.9
