name: Build and deploy to Google App Engine

on:
  push:
    branches:
      - master

# Environment variables
env:
  GAE_PROJECT: ${{ secrets.GAE_PROJECT }}
  GAE_EMAIL: ${{ secrets.GAE_EMAIL }}
  GAE_SA_KEY: ${{ secrets.GAE_SA_KEY }}

jobs:
  setup-build-deploy:
    name: Setup, build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GAE_EMAIL }}
        service_account_key: ${{ secrets.GAE_SA_KEY }}

    - name: Install frontend dependencies
      run: |
        cd vaalikartta-frontend
        npm install --only=production

    - name: Build frontend and move it to `backend` folder
      run: |
        cd ./vaalikartta-frontend
        npm run-script build
        mv ./build ../backend/

    - name: Install backend dependencies
      run: |
        cd ./backend
        npm install --only=production

    - name: Deploy to Google App Engine
      run: |
        cd ./backend
        gcloud app deploy --project=$GAE_PROJECT
